### ISSUE TITLE
Search Input Doesn't Keep Focus on Re-Renders

### ISSUE THREAD

**Issue by manavm1990** [Claim-Academy-JS/parcel-product-search#1]
Each time we type in the search input, after it _renders,_ it loses 'focus.' We have to keep clicking in the field to type the next letter. 😖

**Comment by LDRMuse** [comment]
Not really sure but this is how I created a search bar filter. Maybe this can help? It's also using TypeScript.

// filtering through the menu when the user types in search menu
   filterMenu = (arr: Menu[], letter: string): Menu[] => (
    arr.filter((obj) => (
      Object.values(obj)
        .some((value) => (
          `${value}`.toLowerCase().includes(`${letter}`.toLowerCase())
        ))
    ))
  );


// gets called on (change)
  handleSearch(): void {
    // hides full menu when a change happens (user types in search bar) & removes font awesome icon when input is typed
    // as this hides the full menu - the filtered menu displays
    document.getElementById('fullMenu').classList.add('hidden');
    document.getElementById('searchInput').classList.remove('fas');
    const letter = (document.getElementById('searchInput') as HTMLInputElement).value.toLowerCase();
    // name this function searchMenu so that we can iterate over the filtered menus object in the HTML
    this.searchMenu = this.filterMenu(this.menus, letter);
    // if there's no letter, then display the font-awesome font and icon
    if (!letter) {
      document.getElementById('searchInput').classList.add('fas');
    }
  }

**Comment by manavm1990** [comment]
Thanks @LDRMuse. This particular exercise was to just use vanilla JS with `parcel` only. Surely we'll get it working when we move over to `react`.
